version: '3'

services:
  chubby-service:
    container_name: chubby-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - APP_SETTINGS=development
      - FLASK_APP=run.py
      - GITHUB_API_KEY=${GITHUB_API_KEY}